name: client
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  protobuf: ^2.0.1
  tart:
    path: ../../tart/

dev_dependencies:
  lints: ^1.0.0
